# Generated by Django 3.2 on 2021-07-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
